/* This file was generated by the Hex-Rays decompiler version 8.2.0.221215.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>

//----- (08048444) --------------------------------------------------------
int __cdecl __noreturn main(int argc, const char **argv, const char **envp)
{
	char s[100]; // [esp+28h] [ebp-70h] BYREF
	unsigned int i; // [esp+8Ch] [ebp-Ch]

	i = 0;
	fgets(s, 100, stdin);
	for ( i = 0; i < strlen(s); ++i )
	{
		if ( s[i] > 64 && s[i] <= 90 )
			s[i] ^= 0x20u; // 0x20 = 32
	}
	printf(s);
	exit(0);
}
// 8048444: using guessed type char s[100];